name: Build and Deploy NestJS

on:
  push:
    branches:
      - develop
env:
  mode: dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      # Step 3: Build the NestJS application
      - name: Build the application
        run: |
          npm run build:staging

      # Step 4: Package the build into an artifact
      - name: Package the build into an artifact
        run: |
          mkdir -p artifacts
          cp server.js package.json package-lock.json dist/browser

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/browser
          include-hidden-files: true
          overwrite: true
